defaults:
  - _self_
  - data: fixed_mpcrl_lead
  - net: observation
  - override hydra/launcher: joblib  # This is to parallelize jobs in multirun.

name: ${now:%H-%M-%S}
logpath: experiments/${now:%Y-%m-%d}/${name}
tensorboard: tensorboard

#  A list of all cuda devices we are allowed to use
devices: [0,1,2,3,4,5,6,7]

device: '${assign_device:${hydra:job.num} , ${devices}}'  # Assigns jobs in multi-runs to different gpus, for single runs uses gpu 0. If no gpu -> use cpu

learn:
  epochs: 400  # The number of training steps.
  lr: 0.01

hydra:
  run:
    dir: ${logpath}
  sweep:
    dir: ${logpath}
    subdir: ${hydra.job.num}
  job:
    num: 0
  launcher:
    # This now works with different gpus (using assign_device resolver)
    n_jobs: 30  # number of parallel jobs
