demo_dir: demos
plot_dir: plots
flex_param_file_path: models/three_dof/flexible_link_params_test.yml                # path to the flexible parameter file
seed: 0
n_demos: 100                                                                         # number of demos to collect
render: False                                                                       # render the environment while collecting demos
collect_demos: False                                                                 # if False, then load from demos
random_goal: False                                                                  # if True, then goal is sampled randomly, otherwise goal is chosen near the wall
more_flexible: False

collect_bc: False                                                                    # if False, then load from demos
bc_model_path: trained_models/IL/BC/2023-09-04_14-44/SEED_0/best_model.pt

collect_dagger: False                                                                # if False, then load from demos
dagger_model_path: trained_models/IL/DAGGER/2023-09-04_14-44/SEED_0/best_model.pt

collect_gail: False                                                                  # if False, then load from demos
gail_model_path: trained_models/IRL/GAIL/2023-09-04_14-44/SEED_0/best_model.zip

collect_airl: False                                                                  # if False, then load from demos
airl_model_path: trained_models/IRL/AIRL/2023-09-04_14-44/SEED_0/best_model.zip

collect_density: False                                                               # if False, then load from demos
density_model_path: trained_models/IRL/DENSITY/2023-09-04_14-44/SEED_0/best_model.zip

collect_sac: False                                                                   # if False, then load from demos
sac_model_path: trained_models/RL/SAC/2023-09-04_14-44/SEED_0/best_model.zip

collect_ppo: False                                                                   # if False, then load from demos
ppo_model_path: trained_models/RL/PPO/2023-09-05_11-18/SEED_0/best_model.zip

collect_sac_sf: False                                                                # if False, then load from demos

collect_dagger_sf: False                                                             # if False, then load from demos

collect_mpc: False                                                                   # if False, then load from demos


# plots / measures
distance_box_plot: True                                                                      # plot box plot
distance_constraint_time_scatter_plot: False                                                   # plot scatter plot
