/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) flexible_arm_nq5_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};

/* eval_aba:(i0[5],i1[5],i2[5])->(o0[5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a8, a9;
  a0=arg[2]? arg[2][0] : 0;
  a1=9.9999968293183472e-01;
  a2=arg[0]? arg[0][1] : 0;
  a3=sin(a2);
  a3=(a1*a3);
  a2=cos(a2);
  a1=(a1*a2);
  a2=arg[1]? arg[1][0] : 0;
  a4=(a1*a2);
  a5=1.0248051699999999e-03;
  a6=arg[1]? arg[1][1] : 0;
  a7=7.9632671073326389e-04;
  a8=(a7*a2);
  a8=(a6+a8);
  a9=(a5*a8);
  a10=1.2500000000000000e-01;
  a11=1.9675000000000001e-01;
  a12=(a10*a8);
  a12=(a11*a12);
  a12=(a10*a12);
  a9=(a9+a12);
  a12=(a4*a9);
  a13=1.0657291700000000e-03;
  a14=(a13*a4);
  a15=(a10*a4);
  a15=(a11*a15);
  a15=(a10*a15);
  a14=(a14+a15);
  a15=(a8*a14);
  a12=(a12-a15);
  a15=arg[0]? arg[0][2] : 0;
  a16=cos(a15);
  a17=(a16*a4);
  a15=sin(a15);
  a2=(a3*a2);
  a18=(a15*a2);
  a17=(a17-a18);
  a18=arg[1]? arg[1][2] : 0;
  a19=(a18+a8);
  a20=(a5*a19);
  a21=2.5000000000000000e-01;
  a22=(a21*a8);
  a23=(a16*a22);
  a24=(a10*a19);
  a24=(a23+a24);
  a24=(a11*a24);
  a25=(a10*a24);
  a20=(a20+a25);
  a25=(a17*a20);
  a26=(a13*a17);
  a27=(a21*a4);
  a28=(a10*a17);
  a28=(a27+a28);
  a28=(a11*a28);
  a29=(a10*a28);
  a26=(a26+a29);
  a29=(a19*a26);
  a25=(a25-a29);
  a29=(a27*a24);
  a30=(a23*a28);
  a29=(a29-a30);
  a25=(a25+a29);
  a29=arg[0]? arg[0][3] : 0;
  a30=cos(a29);
  a31=(a30*a17);
  a29=sin(a29);
  a32=(a16*a2);
  a33=(a15*a4);
  a32=(a32+a33);
  a33=(a29*a32);
  a31=(a31-a33);
  a33=arg[1]? arg[1][3] : 0;
  a34=(a33+a19);
  a35=(a5*a34);
  a36=(a21*a19);
  a36=(a23+a36);
  a37=(a30*a36);
  a22=(a15*a22);
  a38=(a29*a22);
  a37=(a37-a38);
  a38=(a10*a34);
  a38=(a37+a38);
  a38=(a11*a38);
  a39=(a10*a38);
  a35=(a35+a39);
  a39=(a31*a35);
  a40=(a13*a31);
  a41=(a21*a17);
  a41=(a27+a41);
  a42=(a10*a31);
  a42=(a41+a42);
  a42=(a11*a42);
  a43=(a10*a42);
  a40=(a40+a43);
  a43=(a34*a40);
  a39=(a39-a43);
  a43=(a41*a38);
  a44=(a37*a42);
  a43=(a43-a44);
  a39=(a39+a43);
  a43=arg[0]? arg[0][4] : 0;
  a44=cos(a43);
  a45=(a44*a31);
  a43=sin(a43);
  a46=(a30*a32);
  a47=(a29*a17);
  a46=(a46+a47);
  a47=(a43*a46);
  a45=(a45-a47);
  a47=arg[1]? arg[1][4] : 0;
  a48=(a47+a34);
  a5=(a5*a48);
  a49=(a21*a34);
  a49=(a37+a49);
  a50=(a44*a49);
  a51=(a30*a22);
  a36=(a29*a36);
  a51=(a51+a36);
  a36=(a43*a51);
  a50=(a50-a36);
  a36=(a10*a48);
  a36=(a50+a36);
  a36=(a11*a36);
  a52=(a10*a36);
  a5=(a5+a52);
  a52=(a45*a5);
  a13=(a13*a45);
  a53=(a21*a31);
  a53=(a41+a53);
  a54=(a10*a45);
  a54=(a53+a54);
  a54=(a11*a54);
  a10=(a10*a54);
  a13=(a13+a10);
  a10=(a48*a13);
  a52=(a52-a10);
  a10=(a53*a36);
  a55=(a50*a54);
  a10=(a10-a55);
  a52=(a52+a10);
  a10=4.1055166700000069e-05;
  a55=(a47*a45);
  a55=(a10*a55);
  a52=(a52+a55);
  a55=(a44*a52);
  a56=(a44*a46);
  a57=(a43*a31);
  a56=(a56+a57);
  a57=(a10*a56);
  a58=(a48*a57);
  a5=(a56*a5);
  a58=(a58-a5);
  a5=(a44*a51);
  a49=(a43*a49);
  a5=(a5+a49);
  a49=(a5*a54);
  a59=(a11*a5);
  a53=(a53*a59);
  a49=(a49-a53);
  a58=(a58+a49);
  a49=4.1399479200000004e-03;
  a53=(a47*a56);
  a60=(a49*a53);
  a58=(a58-a60);
  a60=(a43*a58);
  a55=(a55-a60);
  a39=(a39+a55);
  a55=(a10*a44);
  a60=(a55*a44);
  a61=(a49*a43);
  a62=(a61*a43);
  a60=(a60+a62);
  a60=(a10+a60);
  a62=(a33*a31);
  a63=(a60*a62);
  a55=(a55*a43);
  a61=(a61*a44);
  a55=(a55-a61);
  a61=-2.4593750000000001e-02;
  a64=(a61*a43);
  a65=(a21*a64);
  a55=(a55+a65);
  a65=(a33*a46);
  a66=(a55*a65);
  a63=(a63-a66);
  a39=(a39+a63);
  a63=(a30*a39);
  a66=(a10*a46);
  a67=(a34*a66);
  a35=(a46*a35);
  a67=(a67-a35);
  a35=(a51*a42);
  a68=(a11*a51);
  a41=(a41*a68);
  a35=(a35-a41);
  a67=(a67+a35);
  a52=(a43*a52);
  a58=(a44*a58);
  a52=(a52+a58);
  a58=(a56*a36);
  a35=(a45*a59);
  a58=(a58-a35);
  a53=(a61*a53);
  a58=(a58-a53);
  a53=(a21*a58);
  a52=(a52-a53);
  a67=(a67+a52);
  a52=(a10*a43);
  a53=(a52*a44);
  a35=(a49*a44);
  a41=(a35*a43);
  a53=(a53-a41);
  a41=(a21*a64);
  a53=(a53+a41);
  a41=(a53*a62);
  a52=(a52*a43);
  a35=(a35*a44);
  a52=(a52+a35);
  a35=(a61*a44);
  a69=(a21*a35);
  a52=(a52-a69);
  a69=-4.9187500000000002e-02;
  a69=(a69+a35);
  a35=(a21*a69);
  a52=(a52-a35);
  a52=(a49+a52);
  a35=(a52*a65);
  a41=(a41-a35);
  a67=(a67+a41);
  a41=(a29*a67);
  a63=(a63-a41);
  a25=(a25+a63);
  a63=(a30*a60);
  a41=(a29*a53);
  a63=(a63-a41);
  a41=(a63*a30);
  a35=(a30*a55);
  a70=(a29*a52);
  a35=(a35-a70);
  a70=(a35*a29);
  a41=(a41-a70);
  a41=(a10+a41);
  a70=(a18*a17);
  a71=(a41*a70);
  a63=(a63*a29);
  a35=(a35*a30);
  a63=(a63+a35);
  a35=(a64*a30);
  a69=(a61+a69);
  a72=(a69*a29);
  a35=(a35+a72);
  a72=(a21*a35);
  a63=(a63+a72);
  a72=(a18*a32);
  a73=(a63*a72);
  a71=(a71-a73);
  a25=(a25+a71);
  a71=(a16*a25);
  a73=(a10*a32);
  a74=(a19*a73);
  a20=(a32*a20);
  a74=(a74-a20);
  a20=(a22*a28);
  a75=(a11*a22);
  a27=(a27*a75);
  a20=(a20-a27);
  a74=(a74+a20);
  a39=(a29*a39);
  a67=(a30*a67);
  a39=(a39+a67);
  a67=(a46*a38);
  a20=(a31*a68);
  a67=(a67-a20);
  a67=(a67+a58);
  a62=(a64*a62);
  a65=(a69*a65);
  a62=(a62+a65);
  a67=(a67-a62);
  a62=(a21*a67);
  a39=(a39-a62);
  a74=(a74+a39);
  a60=(a29*a60);
  a53=(a30*a53);
  a60=(a60+a53);
  a53=(a60*a30);
  a55=(a29*a55);
  a52=(a30*a52);
  a55=(a55+a52);
  a52=(a55*a29);
  a53=(a53-a52);
  a52=(a21*a35);
  a53=(a53+a52);
  a52=(a53*a70);
  a60=(a60*a29);
  a55=(a55*a30);
  a60=(a60+a55);
  a69=(a69*a30);
  a64=(a64*a29);
  a69=(a69-a64);
  a64=(a21*a69);
  a60=(a60-a64);
  a64=-9.8375000000000004e-02;
  a64=(a64+a69);
  a69=(a21*a64);
  a60=(a60-a69);
  a60=(a49+a60);
  a69=(a60*a72);
  a52=(a52-a69);
  a74=(a74+a52);
  a52=(a15*a74);
  a71=(a71-a52);
  a12=(a12+a71);
  a71=(a16*a41);
  a52=(a15*a53);
  a71=(a71-a52);
  a52=(a71*a16);
  a69=(a16*a63);
  a55=(a15*a60);
  a69=(a69-a55);
  a55=(a69*a15);
  a52=(a52-a55);
  a52=(a10+a52);
  a55=(a6*a4);
  a39=(a52*a55);
  a71=(a71*a15);
  a69=(a69*a16);
  a71=(a71+a69);
  a69=(a35*a16);
  a64=(a61+a64);
  a62=(a64*a15);
  a69=(a69+a62);
  a62=(a21*a69);
  a71=(a71+a62);
  a6=(a6*a2);
  a62=(a71*a6);
  a39=(a39-a62);
  a12=(a12+a39);
  a12=(a3*a12);
  a10=(a10*a2);
  a8=(a8*a10);
  a9=(a2*a9);
  a8=(a8-a9);
  a25=(a15*a25);
  a74=(a16*a74);
  a25=(a25+a74);
  a74=(a32*a24);
  a9=(a17*a75);
  a74=(a74-a9);
  a74=(a74+a67);
  a70=(a35*a70);
  a72=(a64*a72);
  a70=(a70+a72);
  a74=(a74-a70);
  a74=(a21*a74);
  a25=(a25-a74);
  a8=(a8+a25);
  a41=(a15*a41);
  a53=(a16*a53);
  a41=(a41+a53);
  a53=(a41*a16);
  a63=(a15*a63);
  a60=(a16*a60);
  a63=(a63+a60);
  a60=(a63*a15);
  a53=(a53-a60);
  a60=(a21*a69);
  a53=(a53+a60);
  a55=(a53*a55);
  a41=(a41*a15);
  a63=(a63*a16);
  a41=(a41+a63);
  a64=(a64*a16);
  a35=(a35*a15);
  a64=(a64-a35);
  a35=(a21*a64);
  a41=(a41-a35);
  a35=-1.4756250000000001e-01;
  a35=(a35+a64);
  a64=(a21*a35);
  a41=(a41-a64);
  a49=(a49+a41);
  a6=(a49*a6);
  a55=(a55-a6);
  a8=(a8+a55);
  a8=(a1*a8);
  a55=arg[2]? arg[2][1] : 0;
  a6=(a7*a55);
  a8=(a8+a6);
  a12=(a12+a8);
  a0=(a0-a12);
  a12=1.1250000000000000e-02;
  a52=(a3*a52);
  a53=(a1*a53);
  a52=(a52+a53);
  a52=(a52*a3);
  a71=(a3*a71);
  a49=(a1*a49);
  a71=(a71+a49);
  a71=(a71*a1);
  a52=(a52+a71);
  a12=(a12+a52);
  a0=(a0/a12);
  a52=9.8100000000000005e+00;
  a61=(a61+a35);
  a61=(a7*a61);
  a61=(a61*a1);
  a69=(a7*a69);
  a69=(a69*a3);
  a61=(a61-a69);
  a61=(a61/a12);
  a61=(a52*a61);
  a0=(a0-a61);
  if (res[0]!=0) res[0][0]=a0;
  a2=(a2*a14);
  a4=(a4*a10);
  a2=(a2-a4);
  a4=arg[2]? arg[2][2] : 0;
  a10=(a47*a50);
  a10=(a11*a10);
  a14=(a45*a54);
  a61=(a48*a36);
  a14=(a14+a61);
  a10=(a10-a14);
  a14=(a44*a10);
  a48=(a48*a59);
  a54=(a56*a54);
  a48=(a48+a54);
  a54=5.9999039966568439e+00;
  a61=arg[2]? arg[2][4] : 0;
  a56=(a56*a13);
  a45=(a45*a57);
  a56=(a56-a45);
  a36=(a5*a36);
  a50=(a50*a59);
  a36=(a36-a50);
  a56=(a56+a36);
  a56=(a61-a56);
  a36=(a54*a56);
  a50=4.9189861082220759e-02;
  a47=(a47*a5);
  a5=(a50*a47);
  a36=(a36-a5);
  a48=(a48+a36);
  a36=(a43*a48);
  a14=(a14-a36);
  a36=(a31*a42);
  a5=(a34*a38);
  a36=(a36+a5);
  a14=(a14-a36);
  a36=(a11*a44);
  a5=(a36*a44);
  a59=(a50*a43);
  a45=(a59*a43);
  a5=(a5+a45);
  a5=(a11+a5);
  a45=(a11*a43);
  a57=(a45*a44);
  a50=(a50*a44);
  a13=(a50*a43);
  a57=(a57-a13);
  a13=(a21*a57);
  a12=-3.4694469519536142e-18;
  a69=(a12*a43);
  a13=(a13-a69);
  a69=4.0990239200000000e-03;
  a12=(a12*a44);
  a35=(a21*a12);
  a45=(a45*a43);
  a50=(a50*a44);
  a45=(a45+a50);
  a50=(a21*a45);
  a50=(a50+a12);
  a12=(a21*a50);
  a35=(a35+a12);
  a35=(a69+a35);
  a12=(a13/a35);
  a71=(a12*a13);
  a5=(a5-a71);
  a71=(a33*a37);
  a49=(a5*a71);
  a36=(a36*a43);
  a59=(a59*a44);
  a36=(a36-a59);
  a59=2.4593750000000001e-02;
  a50=(a59+a50);
  a53=(a12*a50);
  a36=(a36-a53);
  a33=(a33*a51);
  a53=(a36*a33);
  a49=(a49-a53);
  a53=arg[2]? arg[2][3] : 0;
  a40=(a46*a40);
  a31=(a31*a66);
  a40=(a40-a31);
  a51=(a51*a38);
  a37=(a37*a68);
  a51=(a51-a37);
  a40=(a40+a51);
  a10=(a43*a10);
  a48=(a44*a48);
  a10=(a10+a48);
  a48=(a21*a10);
  a61=(a61+a48);
  a40=(a40+a61);
  a40=(a53-a40);
  a61=(a12*a40);
  a49=(a49+a61);
  a14=(a14+a49);
  a49=(a30*a14);
  a34=(a34*a68);
  a46=(a46*a42);
  a34=(a34+a46);
  a34=(a34+a10);
  a10=(a50/a35);
  a13=(a10*a13);
  a57=(a57-a13);
  a13=(a57*a71);
  a45=(a11+a45);
  a50=(a10*a50);
  a45=(a45-a50);
  a50=(a45*a33);
  a13=(a13-a50);
  a50=(a10*a40);
  a13=(a13+a50);
  a34=(a34+a13);
  a13=(a29*a34);
  a49=(a49-a13);
  a13=(a17*a28);
  a50=(a19*a24);
  a13=(a13+a50);
  a49=(a49-a13);
  a13=(a30*a5);
  a50=(a29*a57);
  a13=(a13-a50);
  a50=(a13*a30);
  a46=(a30*a36);
  a42=(a29*a45);
  a46=(a46-a42);
  a42=(a46*a29);
  a50=(a50-a42);
  a50=(a11+a50);
  a5=(a29*a5);
  a57=(a30*a57);
  a5=(a5+a57);
  a57=(a5*a30);
  a36=(a29*a36);
  a45=(a30*a45);
  a36=(a36+a45);
  a45=(a36*a29);
  a57=(a57-a45);
  a45=(a21*a57);
  a5=(a5*a29);
  a36=(a36*a30);
  a5=(a5+a36);
  a36=(a21*a5);
  a42=(a21*a36);
  a42=(a69+a42);
  a68=(a45/a42);
  a61=(a68*a45);
  a50=(a50-a61);
  a61=(a18*a23);
  a48=(a50*a61);
  a13=(a13*a29);
  a46=(a46*a30);
  a13=(a13+a46);
  a36=(a59+a36);
  a46=(a68*a36);
  a13=(a13-a46);
  a18=(a18*a22);
  a46=(a13*a18);
  a48=(a48-a46);
  a26=(a32*a26);
  a17=(a17*a73);
  a26=(a26-a17);
  a22=(a22*a24);
  a23=(a23*a75);
  a22=(a22-a23);
  a26=(a26+a22);
  a14=(a29*a14);
  a34=(a30*a34);
  a14=(a14+a34);
  a34=(a21*a14);
  a53=(a53+a34);
  a26=(a26+a53);
  a26=(a4-a26);
  a53=(a68*a26);
  a48=(a48+a53);
  a49=(a49+a48);
  a49=(a15*a49);
  a19=(a19*a75);
  a32=(a32*a28);
  a19=(a19+a32);
  a19=(a19+a14);
  a14=(a36/a42);
  a45=(a14*a45);
  a57=(a57-a45);
  a45=(a57*a61);
  a11=(a11+a5);
  a36=(a14*a36);
  a11=(a11-a36);
  a36=(a11*a18);
  a45=(a45-a36);
  a36=(a14*a26);
  a45=(a45+a36);
  a19=(a19+a45);
  a19=(a16*a19);
  a49=(a49+a19);
  a49=(a21*a49);
  a4=(a4+a49);
  a2=(a2+a4);
  a55=(a55-a2);
  a50=(a15*a50);
  a57=(a16*a57);
  a50=(a50+a57);
  a57=(a50*a15);
  a13=(a15*a13);
  a11=(a16*a11);
  a13=(a13+a11);
  a11=(a13*a16);
  a57=(a57+a11);
  a57=(a21*a57);
  a11=(a21*a57);
  a69=(a69+a11);
  a55=(a55/a69);
  a50=(a50*a16);
  a13=(a13*a15);
  a50=(a50-a13);
  a50=(a21*a50);
  a50=(a50/a69);
  a3=(a52*a3);
  a50=(a50*a3);
  a59=(a59+a57);
  a59=(a59/a69);
  a52=(a52*a1);
  a59=(a59*a52);
  a50=(a50+a59);
  a7=(a7*a0);
  a50=(a50+a7);
  a55=(a55-a50);
  if (res[0]!=0) res[0][1]=a55;
  a26=(a26/a42);
  a42=(a16*a3);
  a7=(a7+a55);
  a55=(a21*a7);
  a52=(a52+a55);
  a55=(a15*a52);
  a42=(a42+a55);
  a61=(a61+a42);
  a68=(a68*a61);
  a16=(a16*a52);
  a15=(a15*a3);
  a16=(a16-a15);
  a16=(a16-a18);
  a14=(a14*a16);
  a68=(a68+a14);
  a68=(a68+a7);
  a26=(a26-a68);
  if (res[0]!=0) res[0][2]=a26;
  a40=(a40/a35);
  a35=(a30*a61);
  a7=(a7+a26);
  a26=(a21*a7);
  a16=(a16+a26);
  a26=(a29*a16);
  a35=(a35+a26);
  a71=(a71+a35);
  a12=(a12*a71);
  a30=(a30*a16);
  a29=(a29*a61);
  a30=(a30-a29);
  a30=(a30-a33);
  a10=(a10*a30);
  a12=(a12+a10);
  a12=(a12+a7);
  a40=(a40-a12);
  if (res[0]!=0) res[0][3]=a40;
  a12=2.4396051828846123e+02;
  a12=(a12*a56);
  a7=(a7+a40);
  a21=(a21*a7);
  a30=(a30+a21);
  a44=(a44*a30);
  a43=(a43*a71);
  a44=(a44-a43);
  a44=(a44-a47);
  a54=(a54*a44);
  a54=(a54+a7);
  a12=(a12-a54);
  if (res[0]!=0) res[0][4]=a12;
  return 0;
}

/* eval_fkp:(i0[5])->(o0[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=2.5000000000000000e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a1=sin(a1);
  a6=7.9632671073326389e-04;
  a3=sin(a3);
  a7=(a6*a3);
  a8=(a1*a7);
  a5=(a5-a8);
  a8=(a0*a5);
  a9=arg[0]? arg[0][2] : 0;
  a10=cos(a9);
  a11=(a5*a10);
  a12=(a2*a3);
  a6=(a6*a4);
  a13=(a1*a6);
  a12=(a12+a13);
  a9=sin(a9);
  a13=(a12*a9);
  a11=(a11-a13);
  a13=(a0*a11);
  a8=(a8+a13);
  a13=arg[0]? arg[0][3] : 0;
  a14=cos(a13);
  a15=(a11*a14);
  a5=(a5*a9);
  a12=(a12*a10);
  a5=(a5+a12);
  a13=sin(a13);
  a12=(a5*a13);
  a15=(a15-a12);
  a12=(a0*a15);
  a8=(a8+a12);
  a12=arg[0]? arg[0][4] : 0;
  a16=cos(a12);
  a15=(a15*a16);
  a11=(a11*a13);
  a5=(a5*a14);
  a11=(a11+a5);
  a12=sin(a12);
  a11=(a11*a12);
  a15=(a15-a11);
  a15=(a0*a15);
  a8=(a8+a15);
  if (res[0]!=0) res[0][0]=a8;
  a8=(a1*a4);
  a7=(a2*a7);
  a8=(a8+a7);
  a7=(a0*a8);
  a15=(a8*a10);
  a2=(a2*a6);
  a1=(a1*a3);
  a2=(a2-a1);
  a1=(a2*a9);
  a15=(a15+a1);
  a1=(a0*a15);
  a7=(a7+a1);
  a1=(a15*a14);
  a2=(a2*a10);
  a8=(a8*a9);
  a2=(a2-a8);
  a8=(a2*a13);
  a1=(a1+a8);
  a8=(a0*a1);
  a7=(a7+a8);
  a1=(a1*a16);
  a2=(a2*a14);
  a15=(a15*a13);
  a2=(a2-a15);
  a2=(a2*a12);
  a1=(a1+a2);
  a1=(a0*a1);
  a7=(a7+a1);
  if (res[0]!=0) res[0][1]=a7;
  a7=1.4999999999999999e-01;
  a1=9.9999968293183472e-01;
  a3=(a1*a3);
  a2=(a0*a3);
  a7=(a7+a2);
  a2=(a3*a10);
  a1=(a1*a4);
  a4=(a1*a9);
  a2=(a2+a4);
  a4=(a0*a2);
  a7=(a7+a4);
  a4=(a2*a14);
  a1=(a1*a10);
  a3=(a3*a9);
  a1=(a1-a3);
  a3=(a1*a13);
  a4=(a4+a3);
  a3=(a0*a4);
  a7=(a7+a3);
  a4=(a4*a16);
  a1=(a1*a14);
  a2=(a2*a13);
  a1=(a1-a2);
  a1=(a1*a12);
  a4=(a4+a1);
  a0=(a0*a4);
  a7=(a7+a0);
  if (res[0]!=0) res[0][2]=a7;
  return 0;
}

/* flexible_arm_nq5_impl_dae_fun:(i0[10],i1[10],i2[3],i3[3],i4[])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+76, *w1=w+86, *w2=w+91, *w3=w+96, *w4=w+99, w5, w6, w7, w8, w9, *w10=w+106, *w11=w+111, *w12=w+116, *w13=w+126;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 10, w0);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+5 : 0, 5, w1);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 5, w2);
  /* #3: @3 = input[2][0] */
  casadi_copy(arg[2], 3, w3);
  /* #4: @4 = @3[:2] */
  for (rr=w4, ss=w3+0; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #5: @5 = -12.67 */
  w5 = -1.2670000000000000e+01;
  /* #6: @6 = @2[2] */
  for (rr=(&w6), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #7: @5 = (@5*@6) */
  w5 *= w6;
  /* #8: @6 = 0.0567 */
  w6 = 5.6700000000000000e-02;
  /* #9: @7 = @1[2] */
  for (rr=(&w7), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #10: @6 = (@6*@7) */
  w6 *= w7;
  /* #11: @5 = (@5-@6) */
  w5 -= w6;
  /* #12: @6 = @3[2] */
  for (rr=(&w6), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #13: @7 = -12.67 */
  w7 = -1.2670000000000000e+01;
  /* #14: @8 = @2[4] */
  for (rr=(&w8), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #15: @7 = (@7*@8) */
  w7 *= w8;
  /* #16: @8 = 0.0567 */
  w8 = 5.6700000000000000e-02;
  /* #17: @9 = @1[4] */
  for (rr=(&w9), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #18: @8 = (@8*@9) */
  w8 *= w9;
  /* #19: @7 = (@7-@8) */
  w7 -= w8;
  /* #20: @10 = vertcat(@4, @5, @6, @7) */
  rr=w10;
  for (i=0, cs=w4; i<2; ++i) *rr++ = *cs++;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #21: @11 = eval_aba(@2, @1, @10) */
  arg1[0]=w2;
  arg1[1]=w1;
  arg1[2]=w10;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #22: @12 = vertcat(@1, @11) */
  rr=w12;
  for (i=0, cs=w1; i<5; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<5; ++i) *rr++ = *cs++;
  /* #23: @0 = (@0-@12) */
  for (i=0, rr=w0, cs=w12; i<10; ++i) (*rr++) -= (*cs++);
  /* #24: output[0][0] = @0 */
  casadi_copy(w0, 10, res[0]);
  /* #25: @3 = input[3][0] */
  casadi_copy(arg[3], 3, w3);
  /* #26: @13 = eval_fkp(@2) */
  arg1[0]=w2;
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #27: @3 = (@3-@13) */
  for (i=0, rr=w3, cs=w13; i<3; ++i) (*rr++) -= (*cs++);
  /* #28: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int flexible_arm_nq5_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int flexible_arm_nq5_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int flexible_arm_nq5_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void flexible_arm_nq5_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int flexible_arm_nq5_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void flexible_arm_nq5_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void flexible_arm_nq5_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void flexible_arm_nq5_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int flexible_arm_nq5_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int flexible_arm_nq5_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real flexible_arm_nq5_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* flexible_arm_nq5_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* flexible_arm_nq5_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* flexible_arm_nq5_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* flexible_arm_nq5_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int flexible_arm_nq5_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 129;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
